version: "3.3"
services:
  autogptq:
    build:
      context: .
    stdin_open: true
    tty: true
    volumes:
      - ./models:/app/models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0','1']
              capabilities: [gpu]
